######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 29 16:55:37 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h testenv.h
SOURCES += mainwindow.cpp test.cpp testenv.cpp
