######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 1 13:33:05 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h startDialog.h testenv.h
SOURCES += mainwindow.cpp startDialog.cpp test.cpp testenv.cpp
