######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 29 19:41:23 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h startDialog.h testenv.h
SOURCES += mainwindow.cpp startDialog.cpp test.cpp testenv.cpp
